# Organization

Good file organization and naming is a mighty weapon against chaos. Informative file name and location tells you what it is, why it exists and its relationship with other things. The more self explanatory it can be, the better! README's are great, but don't document something that is self-documenting by definition.

## Project structure

**Good project structure**

```
├── README.md          <- The top-level README.
├── data
│   ├── external       <- Data from third party sources.
│   ├── interim        <- Intermediate data that has been transformed.
│   ├── processed      <- The final, canonical data sets for modeling.
│   └── raw            <- The original, immutable data dump.
│
├── references         <- Data dictionaries, manuals, and all other explanatory materials.
│
├── src                <- Source code for use in this project.
│   ├── data           <- Scripts to download or generate data.
│   │   └── make_dataset.R
│   │
│   ├── clean          <- Scripts to clean data.
│   │   └── clean_dataset.R
│   │
│   └── visualization  <- Scripts to create exploratory and results oriented visualizations
│       └── visualize.R
└── reports            <- Generated QC reports.
    └── figures        <- Generated graphics and figures to be used in reporting.
```
Adapted from Python’s version from [Cookiecutter Data Science](https://drivendata.github.io/cookiecutter-data-science/)

A good project structure encourages practice that make it easier to come back to old work and make the code easily reproducible.

## Organizational tips

A couple of tips from Jenny Bryan's [organization slides](http://www2.stat.duke.edu/~rcs46/lectures_2015/01-markdown-git/slides/organization-slides/organization-slides.pdf) which worth to be mentioned: 

- [A quarantine directory](#a-quarantine-directory)
- [Revoke write permission to raw data files](#revoke-write-permission-to-raw-data-files)
- [A prose directory](#a-prose-directory)
- [File organization reflects input vs outputs and the information flow](#file-organization-reflects-input-vs-outputs-and-the-information-flow)

### [A quarantine directory](#a-quarantine-directory)

If your collaborator send you data with space-containing file names, data in spreadsheet etc that do not fits your standard naming system and practice, you can place those files in a quarantine directory.

The renamed or exported plain text files can be move to your data directory. Record what you did in a README or comments in your code to remind yourself about the file's source, if it is from the outside world in a state that is not ready for your programmatic analysis.

### [Revoke write permission to raw data files](#revoke-write-permission-to-raw-data-files)

So that it will not be accidentally edited by you or someone else.

### [A prose directory](#a-prose-directory)

Sometimes you need a folder to keep key emails, internal documentation, explanations, random documents received. Similar to the quarantine directory, the prose directory can be used to park these things without having to keep the same standard for file names and open formats.

### [File organization should reflect input vs outputs and the information flow](#file-organization-reflects-input-vs-outputs-and-the-information-flow)

`TODO add a figure`


## Naming files

Jenny Bryan also has [good tips in naming files](https://speakerdeck.com/jennybc/how-to-name-files) summarized below.

Good file names are:

- [machine readable](#machine-readable)
- [human readable](#human-readable)
- [orderable](#orderable)

**Good names**

```
2021-05-20_antarctic-penguins.txt
001-248231_myctophidae-gill.jpg
southern-ocean-jellyfish.docx
```

**Bad names**

```
1.txt 
thesis final_Final_FINAL.docx 
nJ7UyiE*.txt 
ça va.txt
```

### [Machine readable](#machine-readable)

Regular expression and globbing friendly

**Avoid:**

- special characters
- spaces
- punctuation
- accented characters
- case sensitivity

**Use:**

- delimiters

File names follow the pattern:

`<date>_<cruise-number>_<location>.pdf`

- `_` underscore delimits units of metadata
- `-` hyphen delimits words for readability

```
~/Desktop/projects/01_cruise-reports ᐅ ls
2018-12-15_PS117_cape-town.pdf
2019-02-09_PS118_punta-arenas.pdf
2019-04-13_PS119_punta-arenas.pdf
2020-06-04_PS122-4_arctic-ocean.pdf
2020-08-12_PS122-5_arctic-ocean.pdf
```

Using globbing/regular expression to narrow file listing:

```
~/Desktop/projects/01_cruise-reports ᐅ ls *arctic*
2020-06-04_PS122-4_arctic-ocean.pdf
2020-08-12_PS122-5_arctic-ocean.pdf
```

### [Human readable](#human-readable)

- Names that tells you about the file content.
- Utilize the slug concept from semantic URLs.

```
2019-01-24_gis_vector.pdf
2019-02-12_gis_maps.pdf
2019-03-16_r_ggplot.pdf
2019-04-23_r_dplyr.pdf
```

### [Orderable](#orderable)

- File names that start with numbers.
- ISO 8601 standard for dates.
- left pad other numbers with zero(s).

Meaningful names start with numbers allow files to be sorted chronologically. Note that date is in ISO 8601 standard format (YYYY-MM-DD).

```
2020-01-14_team-meeting-minutes.txt
2020-02-21_team-meeting-minutes.txt
2020-02-22_managers-meeting-minutes.txt
2020-03-16_team-meeting-minutes.txt
```

If date is in other format such as (DD-MM-YYYY), sorting the files does not provide chronological order of events.

```
14-01-2020_team-meeting-minutes.txt
16-03-2020_team-meeting-minutes.txt
21-02-2020_team-meeting-minutes.txt
22-02-2020_managers-meeting-minutes.txt
```

If files are not meaningful when ordered with date, they can be named with numeric characters first. For instance, a folder of images to be added into another document following a certain sequence.

```
001_myctophidae_diaphus-adenomus.jpg
002_myctophidae_diaphus-agassizii.jpg
...
010_myctophidae_diaphus-danae.jpg
011_myctophidae_diaphus-fragilis.jpg
```

If the file names are not left pad with zeros, the order will not be chronological as depicted in the example below.

```
10_myctophidae_diaphus-danae.jpg
1_myctophidae_diaphus-adenomus.jpg
11_myctophidae_diaphus-fragilis.jpg
2_myctophidae_diaphus-agassizii.jpg
```





