# Multimedia files

Where to publish your multimedia files?

## Specimen images

For non-human specimen images, [Zenodo](https://zenodo.org/) is a good option to host your images because:

- a Digital Object Identifier (DOI) will be assigned to your upload to make it citeable.
- versioning is supported
- huge data storage space 
- and [much more](https://help.zenodo.org/features/)

### Publishing with Zenodo {-}

#### Upload {-}

If you have plenty of images, uploading one folder containing all your images for one specific dataset (corresponds to your dataset that will be published via [IPT](ipt.biodiversity.aq)) is the easiest approach. 

#### Communities {-}

If your upload is an Antarctic biodiversity dataset, please associate the following communities to your upload:

- [SCAR Scientific Committee on Antarctic Research](https://zenodo.org/communities/scar/?page=1&size=20)
- [SCAR Antarctic Biodiversity Portal](https://zenodo.org/communities/scar-biodiversity-aq/?page=1&size=20)

It helps us to trace what are the datasets uploaded and make your dataset more findable.

#### Basic information {-}

##### Title {-}

Please use the same title as your publication in [IPT](ipt.biodiversity.aq) with a suffix `-multimedia`, e.g.: `My title from IPT-multimedia`

#### License {-}

We recommend 
[Creative Commons Attribution 4.0 International](https://creativecommons.org/licenses/by/4.0/) license for the specimen images, where users are free to share and adapt your multimedia but they must give appropriate credit to you, provide a link to the license and indicate if changes were made.

